# Generated by Django 5.0.6 on 2024-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=100, null=True, verbose_name='телеграм ник'),
        ),
    ]
